---
version: '2.1'
services:
  pixelfed_app:
    image: zknt/pixelfed
    restart: unless-stopped
    environment:
      - APP_NAME=${APP_NAME:-"PixelFed"}
      - APP_ENV=${APP_ENV:-local}
      - APP_KEY=${APP_KEY:-S0meR@nd0mStringS0meR@nd0mString}
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_URL=${SCHEME:-http}://${DOMAIN:-pixelfed.localhost}

      - ADMIN_DOMAIN=${DOMAIN:-pixelfed.localhost}
      - APP_DOMAIN=${DOMAIN:-pixelfed.localhost}
      - SESSION_DOMAIN=${DOMAIN:-pixelfed.localhost}
      - TRUST_PROXIES="*"

      - LOG_CHANNEL=stack

      - DB_CONNECTION=mysql
      - DB_HOST=pixelfed_db
      - DB_PORT=3306
      - DB_DATABASE=pixelfed
      - DB_USERNAME=pixelfed
      - DB_PASSWORD=myp@ssw0rd

      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_DRIVER=redis

      - REDIS_HOST=pixelfed_redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379

      - MAIL_DRIVER=${MAIL_DRIVER:-log}
      - MAIL_HOST=${MAIL_HOST:-mail.service.host}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USERNAME=${MAIL_USERNAME:-username}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-password}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION:-tls}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-noreply@ethibox.fr}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME:-"My name"}

      - OPEN_REGISTRATION=${OPEN_REGISTRATION:-true}
      - ENFORCE_EMAIL_VERIFICATION=${ENFORCE_EMAIL_VERIFICATION:-false}

      - MAX_PHOTO_SIZE=15000
      - MAX_CAPTION_LENGTH=150
      - MAX_ALBUM_LENGTH=4

      - HORIZON_DARKMODE=true
      - HORIZON_EMBED=true

      - ACTIVITY_PUB=${ACTIVITY_PUB:-false}
      - REMOTE_FOLLOW=${REMOTE_FOLLOW:-false}
    volumes:
      - /portainer/Files/AppData/Pixelfed/Data:/var/www/storage
    depends_on:
      - pixelfed_db
      - pixelfed_redis
    # The port statement makes Pixelfed run on Port 8080, no SSL.
    # For a real instance you need a frontend proxy instead!
    ports:
      - ${PORT}:80

  pixelfed_db:
    image: zknt/mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=changeMeForProduction
    volumes:
      - /portainer/Files/AppData/Pixelfed/DB:/var/lib/mysql

  pixelfed_redis:
    image: zknt/redis
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Pixelfed/Redis:/data